<?php
namespace IshTapp\Recommendation\Tests;

trait DataArrayTrait
{

  public $table = [ 
        [
            'vacancy_id'=>'A',
            'score'=>1,
            'user_id'=>'Aibek'
        ],
        [
           'vacancy_id'=>'B',
           'score'=>0,
           'user_id'=>'Aibek'
        ],
        [
           'vacancy_id'=>'A',
           'score'=>0,
           'user_id'=>'Maria'
        ],
        [
           'vacancy_id'=>'B',
           'score'=>1,
           'user_id'=>'Maria'
        ],
        [
           'vacancy_id'=>'C',
           'score'=>1,
           'user_id'=>'Kuba'
        ],
        [
          'vacancy_id'=>'A',
          'score'=>1,
          'user_id'=>'Kuba'
        ],
        [
          'vacancy_id'=>'A', 
          'score'=>1,
          'user_id'=>'Bek'
        ],
        [
          'vacancy_id'=>'B', 
          'score'=>0,
          'user_id'=>'Uson'
        ],
        [
          'vacancy_id'=>'C', 
          'score'=>1,
          'user_id'=>'Bek'
        ],
        [
          'vacancy_id'=>'G', 
          'score'=>1,
          'user_id'=>'Aibek'
        ],
        [
          'vacancy_id'=>'A', 
          'score'=>1,
          'user_id'=>'Rustom'
        ],
        [
          'vacancy_id'=>'B', 
          'score'=>1,
          'user_id'=>'Bermet'
        ],
        [
          'vacancy_id'=>'C', 
          'score'=>0,
          'user_id'=>'Rustom'
        ],
        [
         'vacancy_id'=>'G', 
         'score'=>1,
         'user_id'=>'Maria'
        ],
        [
         'vacancy_id'=>'F', 
         'score'=>1,
         'user_id'=>'Bermet'
        ],
        [
         'vacancy_id'=>'B', 
         'score'=>0,
         'user_id'=>'Kuba'
        ],
        [
         'vacancy_id'=>'F', 
         'score'=>1,
         'user_id'=>'Aibek'
        ],
        [
         'vacancy_id'=>'C', 
         'score'=>1,
         'user_id'=>'Lunara'
        ],
        [
         'vacancy_id'=>'F', 
         'score'=>1, 
         'user_id'=>'Lunara'
        ],
        [
         'vacancy_id'=>'B', 
         'score'=>0, 
         'user_id'=>'Lunara'
        ],
        [
         'vacancy_id'=>'B', 
         'score'=>1, 
         'user_id'=>'Rustom'
        ]              
      ];
}